name: Flutter

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: beta
          version: 3.19.0-0.3.pre

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze
