name: Auto Pull Request 

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone repository
        run: git clone https://github.com/BryanIP/calc_flex.git

      - name: Checkout branch
        run: |
          git fetch
          git checkout ${GITHUB_HEAD_REF}
      
      - name: Summary
        run: |
          echo "commit_message = ${GITHUB_HEAD_REF}- $(git log -1 --pretty=%B)
