name: Auto Pull Request 

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SHA Commit
        run: commit_sha="${{github.event.pull_request.head.sha}}"

      - name: Commit Message
        run: commit_message=$(git log -1 --pretty=%B ${commit_sha})
      
      - name: Summary
        run: echo "commit_message = ${env.commit_message}"
