name: Auto Pull Request 

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Message
        run: |
          branch_name = "${{github.head_ref}}"
          commit_message = $(git log -1 --pretty=%B)
          text = "${branch_name} - ${commit_message}"
          echo "commit_message = $text"
