name: Auto Pull Request 

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Commit message
        run:  |
          commit_message = "${{github.head_ref}}"
          echo "commit_message = ${commit_message}"
