name: Auto Pull Request 

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Commit message
        run: echo "The branch name is ${{github.head_ref}}"
